### ISSUE TITLE
Use `.mli` files

### ISSUE THREAD

**Issue by gasche** [reynir/ocaml-ssh-agent#4]
I think it would be nice if your modules came with a well-defined interface in the corresponding `.mli` file. I know that this causes some duplication of type declarations (which I suppose you decided to avoid by just using `types.ml` instead), so you may want to keep `types.ml` without an interface and maybe use `include (module type of Types)` in `ssh_agent.mli`. But if that does not work, personally I think that reproducing type-declaration change twice is a reasonable price to pay compared to having no cleanly defined interface and user documentation.

**Comment by reynir** [comment]
Thank you. I agree. The code has been changing a lot the past week or so, and I wasn't sure what interface I wanted to expose, so I didn't write any `.mli`s or documentation. It's getting close to a state where I'm satisfied with releasing it, so it's definitely about time I do something about it.

For a long time I only had the code in a private repository, and I only published it on github in order to share it with people from the Mirage hack retreat.  :-)

**Comment by reynir** [comment]
Fixed in https://github.com/reynir/ocaml-ssh-agent/pull/9 (although I didn't intend to merge it just yet).
